### ISSUE TITLE
Member not found: 'enumValue'. with latest Flutter 3.24

### ISSUE THREAD

**Issue by mhdjazmati** [IO-Design-Team/hive_ce#21]
**Steps to Reproduce**
upgrade flutter to latest version, run app

../../../.pub-cache/hosted/pub.dev/hive_ce-2.5.0+2/lib/src/annotations/hive_field.dart:8:14: Error: Member not found: 'enumValue'.
  TargetKind.enumValue

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: [3.24.2]
 - Hive version: [2.5.0+2]

**Comment by Rexios80** [comment]
Try running

```
flutter clean
flutter pub get
```

**Comment by mhdjazmati** [comment]
if i roll back to flutter 3.20 its working, 3.24 not working

**Comment by Rexios80** [comment]
Do you mind sharing your pubspec? I've been using flutter 3.24 for a while with no issue. I'm not sure how this would be possible unless you have a dependency override on meta or something.

**Comment by Rexios80** [comment]
I'm definitely not able to reproduce this on Flutter 3.24.3

As a last resort, you could delete your pub cache

**Comment by mhdjazmati** [comment]
yes i have meta ovveride acctully:

dependencies:

  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8  # Supports Android and iOS

  # Network and API
  connectivity_plus: ^6.0.3  # Provides cross-platform network connectivity information
  dio: ^5.5.0+1  # HTTP client for Dart

  # State Management
  get: ^4.6.6 # State management library for Flutter

  # syncfusion libs
  syncfusion_flutter_datepicker: ^26.1.42  # Date picker
  syncfusion_flutter_calendar: ^26.1.42   # Calendar widget
  syncfusion_flutter_datagrid: ^26.1.42
  syncfusion_flutter_charts: ^26.1.42  # Data visualization library
  syncfusion_flutter_sliders: ^26.1.42  # Range sliders
  syncfusion_flutter_pdfviewer: ^26.1.42   # PDF viewer widget
  syncfusion_localizations: ^26.1.42


  # UI and Graphics
  pro_image_editor: ^4.2.7
  material_design_icons_flutter: ^7.0.7296  # Material Design icons
  flutter_svg: ^2.0.10+1  # Renders SVG images in Flutter  # Supports Android, iOS, and Web
  flutter_spinkit: ^5.2.1  # Collection of loading indicators
  url_launcher: ^6.3.0  # Opens URLs in the default browser
  mobile_scanner: ^5.1.1  # QR code scanner  # Supports Android and iOS
  local_auth: ^2.2.0  # Fingerprint authentication and biometrics  # Supports Android and iOS
  google_fonts: ^6.2.1  # Access to Google Fonts in Flutter
  cached_network_image: ^3.3.1
  signature: ^5.5.0  # Capture and display user signatures
  flutter_html: ^3.0.0-beta.2  # Renders HTML content in Flutter
  htmltopdfwidgets: ^1.0.3
  sticky_headers: ^0.3.0+2  # Sticky headers in lists
  math_expressions: ^2.5.0  # Parse and evaluate math expressions

  # User Interfacecached_network_image: ^3.3.0
  flutter_speed_dial: ^7.0.0  # Floating action button with speed dial
  jsonlogic:
    git:
      url: https://github.com/malek29/jsonlogic.git
      ref: feature/support-check-datetime
  flutter_material_pickers: ^3.7.0  # Material design picker dialogs

  dropdown_search: ^5.0.6  # Dropdown search widget
  auto_size_text: ^3.0.0  # Automatically adjusts text size to fit available space
  email_validator: ^3.0.0  # Validates email addresses

  # Data Persistence
  hive: ^2.2.3  # Lightweight and fast NoSQL database
  hive_flutter: ^1.1.0  # Hive integration for Flutter
  get_storage: ^2.1.1 # Lightweight key-value storage for Flutter
  flutter_secure_storage: ^9.2.2 # Flutter Secure Storage provides API to store data in secure storage.
  shared_preferences: ^2.2.3

  # Multimedia
  flutter_staggered_grid_view: ^0.7.0  # Staggered grid view
  dotted_border: ^2.1.0  # Dotted border widget
  image_picker: ^1.1.2  # Image picker
  record: ^5.1.2
  audioplayers: ^6.0.0
  stop_watch_timer: ^3.1.1
  permission_handler: ^11.3.1  # Handles runtime permissions
  path: ^1.9.0  # Provides platform-independent path manipulation
  intl: ^0.19.0  # Internationalization and localization support
  photo_view: ^0.15.0  # Interactive photo viewer
  easy_debounce: ^2.0.3

  # File and Storage
  path_provider: ^2.1.3  # Access to platform-specific directories
  image_compression_flutter: ^1.0.4
  flutter_image_compress: ^2.3.0

  # Desktop
  scrollable_positioned_list: ^0.3.8  # Scrollable and indexable list
  desktop_window: ^0.4.0  # Manipulate the window properties (supports desktop)  # Supports macOS and Linux

  # Miscellaneous
  fluttertoast: ^8.2.6  # Toast notifications
  image_gallery_saver: ^2.0.3  # Save images to the gallery  # Supports Android and iOS

  # Utilities and Helpers
  month_year_picker: ^0.4.0+1
  image_size_getter: ^2.1.3  # Get image dimensions
  units_converter: ^3.0.0  # Converts various units of measurement
  jiffy: ^6.3.1  # Date and time manipulation
  equatable: ^2.0.5  # Simplifies equality comparisons  
  dartz: ^0.10.1  # Functional programming library  
  package_info_plus: ^8.0.0  # Access package information
  device_info_plus: ^10.1.0  # Access device information
  logger: ^2.3.0

  # PDF and Printing
  pdf: ^3.11.0  # PDF document manipulation
  printing: ^5.13.1  # Printing support for Flutter
  file: ^7.0.0  # File manipulation

  # Speech and Audio
  speech_to_text: ^6.6.2  # Speech recognition and synthesis
  avatar_glow: ^3.0.1  # Avatar glow effect

  # Drawing and Effects
  flutter_painter_v2: ^2.0.1

  # String and Time Manipulation
  timeago: ^3.7.0  # Converts DateTime to a fuzzy time string

  # Connectivity and Location
  geolocator: ^12.0.0  # Cross-platform location API

  # Sharing and File Picker
  share_plus: ^9.0.0  # Share content across apps
  file_picker: ^8.0.6  # File picker
  open_file: ^3.3.2

  filesize: ^2.0.1  # Formats file sizes
  universal_io: ^2.2.2  # Universal I/O operations
  universal_html: ^2.2.4
  exif: ^3.3.0
  uuid: ^4.4.2  # Unique identifier generation
  collection: ^1.18.0 #working with collections easier

  # Sentry is used for error tracking and reporting.
  sentry_flutter: ^8.3.0
  rrule: ^0.2.16
  flutter_advanced_switch: ^3.1.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  flutter_localization: ^0.2.0
  flutter_cache_manager: ^3.3.2
  google_mlkit_text_recognition: ^0.13.0
  camera: ^0.11.0+1

  video_thumbnail: ^0.5.3

  #  flutter_inappwebview:
  #    git:
  #      url: https://github.com/pichillilorenzo/flutter_inappwebview.git
  #      ref: feature/flutter_inappwebview_windows
  #  webview_windows: ^0.4.0
  flutter_inappwebview: ^6.0.0
  webview_win_floating: ^2.2.5
  flutter_dotenv: ^5.1.0
  font_awesome_flutter: ^10.7.0
#  getx_translator: ^1.0.3

  windows_ocr:
    path: ../flowdit_flutter/windows_ocr
  
dependency_overrides:
  js: ^0.7.1
  meta: '>=1.11.0 <1.15.0'

dev_dependencies:
  flutter_test:
    sdk: flutter

  # hive
  hive_generator: ^2.0.1  # Hive code generator

  # flutter packages pub run build_runner build

  build_runner: ^2.4.11  # Build runner for code generation
  analyzer: ^6.5.0  # Static code analysis

  json_serializable: ^6.8.0  # JSON serialization

  riverpod_generator: ^2.4.2

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0  # Recommended lints for Flutter
#  custom_lint:
#  my_lints:
#    path: ./my_lints
  #  use_read_secure_for_secure_keys_lint:
  #    path: ./use_read_secure_for_secure_keys_lint
  riverpod_lint: ^2.3.12

**Comment by mhdjazmati** [comment]
dependency_overrides:
  js: ^0.7.1
  meta: '>=1.11.0 <1.15.0'

**Comment by Rexios80** [comment]
enumValue was added in meta 1.15.0 so that's the issue

**Comment by Rexios80** [comment]
Actually it was 1.14.0, but you're probably resolving a lower version. If you can reproduce this without any overrides please reopen it.
