### ISSUE TITLE
Hive exception problem

### ISSUE THREAD

**Issue by Arvikon-RobRiveros** [IO-Design-Team/hive_ce#31]
Hi, I'm getting an Exception at hive_impl.dart when I try to run my project that says
"FileSystemException (FileSystemException: Cannot create file, path = './box_bad_keys.hive' (OS Error: Read-only file system, errno = 30))"

I've tried giving permissions in the AndroidManifest.xml and some other similar solution I've seen but it doesn't work.
Although it works on the web.

If you guys have any idea what it could be, I appreciate it.

Thank you in advance.

**Version**
 - Platform: Android (Tablet emulator and Xiaomi Note9 phone)
 - Flutter version: [3.24.3]
 - Hive version: [hive_ce_flutter: ^2.1.0]

**Comment by Arvikon-RobRiveros** [comment]
In your example the registry adapters are asking for an argument in your example.
We are using these dependencies

dependencies:
  flutter:
    sdk: flutter
  hive_ce: 2.6.0
  hive_ce_flutter: ^2.1.0
  cupertino_icons: ^1.0.8
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_ce_generator: ^1.6.0

**Comment by Rexios80** [comment]
Can you make a sample app that shows the issue you are having?

**Comment by Rexios80** [comment]
Is this the example you tried to run? I had to update gradle, but it works fine on Android for me: https://github.com/IO-Design-Team/hive_ce/blob/main/hive_flutter/example/lib/main.dart

**Comment by Arvikon-RobRiveros** [comment]
Hi, 

Is exactly the example from here
https://pub.dev/packages/hive_ce_flutter/example

We have been testing various things and investigating and we believe it is a permissions issue and not a Hive issue. We have tried granting the permissions in the manifest, through ADB, etc, but still haven't figured out how to fix it.

**Comment by Rexios80** [comment]
How are you initializing hive?

**Comment by Arvikon-RobRiveros** [comment]
Now it's working.

It was necessary to use getApplicationDocumentsDirectory() to initialize hive and then reuse the method to get the path and use it when opening the box ( BoxCollection.open ) as one of the parameters.

Thank you very much for your prompt replies.
