### ISSUE TITLE
introduce the Hive.flush() method

### ISSUE THREAD

**Issue by wenyue** [IO-Design-Team/hive_ce#48]
Can we provide the flush api? This needs to be used in some cases.

**Version**
 - Platform: iOS, Android, Mac, Windows, Linux, Web
 - Flutter version: [e.g. 1.5.4]
 - Hive version: [e.g. 0.5.0]

**Comment by Rexios80** [comment]
Can you elaborate on what cases need this? Also what would this feature do exactly?

**Comment by wenyue** [comment]
For example, before exiting the program, we need to make sure that all the data has been written to the hard disk. We now have a Hive.close() method, but this method call will close all boxes. This needs to ensure that we do not hold a reference to box, it is very difficult to use.

**Comment by wenyue** [comment]
Or can you provide a way to get all the boxes?

**Comment by Rexios80** [comment]
Isn't all data persisted immediately? Have you ever lost data because of this?

**Comment by wenyue** [comment]
Yes, the data is persisted immediately, but I need to make sure that the persistence is complete and not exited on persistence

**Comment by Rexios80** [comment]
Persisting the data should take almost zero seconds. What would cause the app to quit during that time? Where would you call this method?

**Comment by Rexios80** [comment]
Also you could store references to all the futures of write operations and await them. That would basically be what a flush method would be.

**Comment by Rexios80** [comment]
Please reopen this if you have additional details
