### ISSUE TITLE
Box not found. Did you forget to call Hive.openBox()?

### ISSUE THREAD

**Issue by yanashenyang** [IO-Design-Team/hive_ce#58]
════════ Exception caught by widgets library ═══════════════════════════════════
The following HiveError was thrown building PesoAPage(dirty, state: _PesoAPageState#2aea8):
Box not found. Did you forget to call Hive.openBox()?

your code
```
void example() {
  final box = Hive.box('myBox');
  box.put('name', 'David');
  final name = box.get('name');
  print('Name: $name');
}
```

**Comment by Rexios80** [comment]
There is no `Hive.openBox` call in that code

**Comment by Rexios80** [comment]
Feel free to reopen this if you have additional questions
